# Generated by Django 2.0.4 on 2018-04-10 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memos',
            name='name_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memos',
            name='text',
            field=models.TextField(blank=True, help_text='메모 내용은 230자 이내로 입력 가능', max_length=230),
        ),
        migrations.AlterField(
            model_name='memos',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='memos',
            name='update_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
